### ISSUE TITLE
Setters y getters

### ISSUE THREAD

**Issue by alvaroolt** [rnicar245/Reentrega-Examen-Cliente#5]
https://github.com/rnicar245/Reentrega-Examen-Cliente/blob/6521c21a4d952b3c6a4dc3c16b0c4acc7144407b/Empleado.js#L6
No tienes ni setters ni getters en tu clase Empleado

**Comment by rnicar245** [comment]
Los setters no son necesarios ya que no voy a cambiar las propiedades de empleado (a parte del constructor).
