### ISSUE TITLE
Ancho y altura muy grandes

### ISSUE THREAD

**Issue by alvaroolt** [rnicar245/Reentrega-Examen-Cliente#6]
https://github.com/rnicar245/Reentrega-Examen-Cliente/blob/6521c21a4d952b3c6a4dc3c16b0c4acc7144407b/index.js#L12
Queda mal tanto espacio en blanco en la página emergente. No necesitas un width y un height tan excesivos. Probablemente con un 200x300 o algo así sería suficiente y sería más cómodo a la vista.

**Comment by rnicar245** [comment]
Algunos mensajes de error son muy largos, así que solo cambié la altura.
