### ISSUE TITLE
Ancho y altura muy grandes (otra vez)

### ISSUE THREAD

**Issue by alvaroolt** [rnicar245/Reentrega-Examen-Cliente#7]
https://github.com/rnicar245/Reentrega-Examen-Cliente/blob/6521c21a4d952b3c6a4dc3c16b0c4acc7144407b/index.js#L19
Te ocurre lo mismo que en el issue #6, pero con la segunda parte del examen (formulario del empleado).

**Comment by rnicar245** [comment]
Los corregí del revés, pero es lo mismo.
